---
driver:
  name: vagrant
  synced_folders:
    - ["./", "/var/www/simple"]
  network:
    - ["private_network", {ip: "192.168.33.37"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test-app::default]
    attributes:
      test-cookbook:
        foo: baz

