name             'test-app'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures test-app'
long_description 'Installs/Configures test-app'
version          '0.1.0'

depends 'test-cookbook'
depends 'apt'
